// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgnWny2mdfwSXiWp0n_LpF8XDRk35bho',
    appId: '1:688443697597:web:f11773f70f3dd5e5b90ad4',
    messagingSenderId: '688443697597',
    projectId: 'laksi-website-61232',
    authDomain: 'laksi-website-61232.firebaseapp.com',
    storageBucket: 'laksi-website-61232.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7XXCjoZymQ6CkPpzL4cZ432K2DhcSM8',
    appId: '1:688443697597:android:83dea6c53cbd9f53b90ad4',
    messagingSenderId: '688443697597',
    projectId: 'laksi-website-61232',
    storageBucket: 'laksi-website-61232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ANdjPbUe8CB0LGsd_8E7pc7AFdsOjJs',
    appId: '1:688443697597:ios:71fca6d58746c0ecb90ad4',
    messagingSenderId: '688443697597',
    projectId: 'laksi-website-61232',
    storageBucket: 'laksi-website-61232.appspot.com',
    iosBundleId: 'com.example.laksi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ANdjPbUe8CB0LGsd_8E7pc7AFdsOjJs',
    appId: '1:688443697597:ios:b0be020be6032858b90ad4',
    messagingSenderId: '688443697597',
    projectId: 'laksi-website-61232',
    storageBucket: 'laksi-website-61232.appspot.com',
    iosBundleId: 'com.example.laksi.RunnerTests',
  );
}
